# Generated by Django 3.0.8 on 2020-07-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('person', models.CharField(choices=[('1', 'me'), ('2', 'Njan'), ('3', 'Swayam'), ('4', 'Than')], max_length=10)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
