# Generated by Django 3.0.8 on 2020-07-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.CharField(choices=[('Me', 'me'), ('Njan', 'Njan'), ('Swayam', 'Swayam'), ('Than', 'Than')], max_length=10),
        ),
    ]
